### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'urlencode'

### ISSUE THREAD

**Issue by m-vdb** [trbs/statuscake#16]
Using Python 3.6, fails because `urllib.urlencode` doesn't exist. The line of code that fails: https://github.com/trbs/statuscake/blob/master/statuscake/api.py#L97-L97

Resolution: use `six` module compatibility.

**Comment by trbs** [comment]
Thanks for the ticket and PR !

**Comment by m-vdb** [comment]
👍 no problem. Do you think you can make a pypi release soon @trbs ?

**Comment by trbs** [comment]
https://pypi.python.org/pypi/statuscake/1.2.2 :-)

**Comment by m-vdb** [comment]
awesome!
