### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by mgedmin** [trbs/statuscake#2]
Do you have any plans to document this?

Can I help?

**Comment by trbs** [comment]
Honestly at the moment I'm not using StatusCake so I do not have much incentive to work on this repository. 

But I'm more then happy to accept any help (PR's) or give maintenance over to people that are using it.

**Comment by trbs** [comment]
(might be better to leave it open for other people to find :) )

**Comment by tomreyn** [comment]
Maybe @StatusCakeDaniel would be more interested in maintaining this (if this offer still stands)?
