### ISSUE TITLE
ContactGroup tests/update should be a string

### ISSUE THREAD

**Issue by macropin** [trbs/statuscake#20]
`ContactGroup` field in `https://app.statuscake.com/API/Tests/Update` should be a CSV string of ints. 

Official docs (typo and all):

`A contact group ID assoicated with account to use. Comma separation for multiple ID's.`

```diff
--- a/statuscake/api.py
+++ b/statuscake/api.py
@@ -71,7 +71,7 @@ class StatusCake(object):
         'FindString': (six.string_types, None, None),
         'DoNotFind': (int, (0, 1), None),
         'TestType': (six.string_types, ("HTTP", "TCP", "PING"), None),
-        'ContactGroup': (int, None, None),
+        'ContactGroup': (six.string_types, None, to_comma_list),
         'RealBrowser': (int, (0, 1), None),
         'TriggerRate': (int, range(0, 61), None),
         'TestTags': (six.string_types, None, to_comma_list),
```

Also thanks for putting together these bindings, I've found them nice to use (unlike the underlying API which is terrible).

**Comment by macropin** [comment]
Looks like I've needed to fix a bunch of things. Let me know if you're happy to accept a PR and I'll send it through when I'm done.

**Comment by trbs** [comment]
Yes, thanks for the work on this ! happy to accept a PR
