### ISSUE TITLE
Calling update_test with data from a previous get_details_test call throws StatusCakeFieldError

### ISSUE THREAD

**Issue by endrec** [trbs/statuscake#26]
I call `get_details_test` with a valid test_id, and I pass the return dict to `update_test` as data.

**Observed behaviour:**
Various `StatusCakeFieldError`s are thrown, for example:
```
StatusCakeFieldError("Field %s must be of type %s" % (field_name, field_type))
statuscake.exceptions.StatusCakeFieldError: Field TriggerRate must be of type <class 'int'>
```

**Expected behaviour:**
The data returned by the API should be accepted as an input by the API.
Items returned in the dict should have the same type as `update_test` or `create_test` would expect.

**Comment by trbs** [comment]
Thanks for the report !

Honestly I currently do not have the resources to work on `statuscake`.
If you could make a PR, I'm happy to merge any proper fixes.

**Comment by trbs** [comment]
Closing as this ticket is a almost a year old.
