### ISSUE TITLE
Request Time Out Error

### ISSUE THREAD

**Issue by superbhat** [trbs/statuscake#28]
While trying to get_all_tests(), it failing with below error. 
Is there any restriction on the call to be made as im calling the above function more frequently. Was working while ago.

requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='app.statuscake.com', port=443): Read timed out. (read timeout=10)

**Comment by superbhat** [comment]
Im not getting error anymore, however if u can help me what might cause the issue will be great.
Thanks

**Comment by trbs** [comment]
glad to hear the problem solved itself.

sounds like either app.statuscake.com, your network or some part of the internet in between had issues leading to the timeout.
