### ISSUE TITLE
URL changes from *www* to *app*

### ISSUE THREAD

**Issue by juan-monterroza** [trbs/statuscake#4]
We are getting errors when executing this library, SC did some work in the redirection of their old URLs and we need to update the `api.py` to reflect the new ones. I noticed we already tried to fix the URLS in June, but the commit failed.

https://github.com/trbs/statuscake/commit/cb1302f2aa833a28e68b8a70cba89d6c07321b77

**Comment by tomreyn** [comment]
An commit fixing this is already in master, but it appears that a new release and push / commit to PyPI is needed, the latest version there is 1.0.1, uploaded on 2014-12-03.

**Comment by trbs** [comment]
https://pypi.python.org/pypi/statuscake/1.1.0 has been uploaded to pypi :-)
