### ISSUE TITLE
URL_UPDATE_TEST

### ISSUE THREAD

**Issue by r2ronoha** [trbs/statuscake#5]
Hi
There is an issue with the URL_UPDATE_TEST.
It's been moved to "https://app.statuscake.com/Workfloor/SaveTest.php" which causes the update to fail as on redirection the module uses GET instead of PUT, plus the data is lost.
I tried to create a new branch for pull request but I got denied.
It would be great if you could update it

**Comment by trbs** [comment]
Could you create a PR for this ? Then I will merge is asap. (You should fork the repo then create a branch and do a Pull Request on that)

**Comment by tomreyn** [comment]
This seems to have since been solved in master? 
https://github.com/trbs/statuscake/blob/master/statuscake/api.py#L22
